trigger:
  branches:
    include: [main]

pr:
  branches:
    include: [main]

# Usamos el pool self-hosted
pool:
  name: SelfHosted
stages:
  - stage: CI
    displayName: "CI Front + Back (Self-Hosted)"
    jobs:
      # Front
      - job: Build_Front
        displayName: "Build Front"
        steps:
          - checkout: self
            fetchDepth: 0

          - task: NodeTool@0
            inputs:
              versionSpec: "20.x"
            displayName: "Use Node 20.x"

          - script: |
              cd front
              npm install --no-audit --no-fund
              npm run build
            displayName: "Install & Build (front)"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.SourcesDirectory)/front"
              ArtifactName: "front_bundle"
              publishLocation: "Container"
            displayName: "Publish front_bundle (full front/)"

      # --- Back -
      - job: Build_Back
        displayName: "Build Back"
        steps:
          - checkout: self
            fetchDepth: 0

          - task: NodeTool@0
            inputs:
              versionSpec: "20.x"
            displayName: "Use Node 20.x"

          - script: |
              cd back
              npm install --no-audit --no-fund
              npm test --if-present
              npm run build --if-present
            displayName: "Install, Test & Build (back)"

          - task: PublishBuildArtifacts@1
            displayName: "Publish artifact: back_bundle"
            inputs:
              PathtoPublish: "$(Build.SourcesDirectory)/back"
              ArtifactName: "back_bundle"
              publishLocation: "Container"
